# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: pip
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest rzpipe meson==0.62.0 ninja coverage ciphey frida objection

        # Install graphviz & ninja
        sudo apt-get -y install graphviz ninja-build
 
        # Install Rizin
        sudo git clone https://github.com/rizinorg/rizin /opt/rizin/
        cd /opt/rizin/
        sudo git checkout de8a5cac5532845643a52d1231b17a7b34feb50a
        meson build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig -v
        cd -
 
        # Install click >= 8.0.0 for CLI supports
        python -m pip install click==8.0.3

    - name: Install Quark-Engine
      run: |
        python setup.py build
        python setup.py install

    - name: Test with pytest
      run: |
        python -m pip install black pytest sphinx sphinx-rtd-theme
        python -m pip install coveralls codecov pytest-cov
        pytest --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        fail_ci_if_error: true

