# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pipenv'
        cache-dependency-path: |
          **/Pipfile.lock

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock
        pip install meson==0.62.0 ninja
        sudo apt-get install ninja-build

        # Install graphviz
        sudo apt-get -y install graphviz

        # Install Rizin
        sudo git clone --branch v0.3.4 https://github.com/rizinorg/rizin /opt/rizin/
        cd /opt/rizin/
        meson build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig -v
        cd -
        
    - name: Test with pytest
      run: |
        pipenv install pytest-cov ciphey frida --skip-lock
        pipenv run pytest --cov=. --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        fail_ci_if_error: true
        verbose: true
