# This is the basic workflow of using quark-engine

name: Smoke Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        python -m pip install pipenv
        # python -m pip install ciphey frida objection
        pipenv install --dev --skip-lock
        # python -m pip install black pytest sphinx sphinx-rtd-theme
        pipenv install black pytest sphinx sphinx-rtd-theme
        # Install click >= 8.0.0 for CLI supports
        # python -m pip install click==8.0.3

    - run: sudo apt-get -y install graphviz ninja-build
      if: matrix.os == 'ubuntu-latest'
    - run: brew install graphviz ninja
      if: matrix.os == 'macOS-latest'
    - run: choco install graphviz ninja
      if: matrix.os == 'windows-latest'

    - name: Install Quark-Engine
      run: |
        pipenv run python setup.py build
        pipenv run python setup.py install

    # Download the latest rule set
    - name: Download rule from https://github.com/quark-engine/quark-rules
      run: pyenv run --verbose freshquark

    # Runs a set of commands using the quark-engine
    - name: Run a multi-line script
      run: |
        pipenv run --verbose quark --help
        git clone https://github.com/quark-engine/apk-malware-samples
        pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -s
        pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -d
        pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -s -g
        pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -d -g
        pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -s -c
        pipenv run quark -a apk-malware-samples/Ahmyth.apk -s -t 100
    - name: Check Accuracy
      shell: bash
      run: |
        echo "Ahmyth_RESULT=$(pipenv run quark -a apk-malware-samples/Ahmyth.apk -s -t 100 | grep 100% | wc -l | awk '{print $1}')" >> $GITHUB_ENV
        echo "a4db_RESULT=$(pipenv run quark -a apk-malware-samples/13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk -s -t 100 | grep 100% | wc -l | awk '{print $1}')" >> $GITHUB_ENV
        echo "e273e_RESULT=$(pipenv run quark -a apk-malware-samples/14d9f1a92dd984d6040cc41ed06e273e.apk -s -t 100 | grep 100% | wc -l | awk '{print $1}')" >> $GITHUB_ENV
    - name: Check Ahmyt Result
      shell: bash
      # This sample should have 16 behaviors with 100% confidence
      run: |
        if [ "${{ env.Ahmyth_RESULT }}" == "35" ]; then
          exit 0
        else
          exit 1
        fi
    - name: Check 13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk Result
      shell: bash
      # This sample should have 11 behaviors with 100% confidence
      run: |
        if [ "${{ env.a4db_RESULT }}" == "19" ]; then
          exit 0
        else
          exit 1
        fi
    - name: Check 14d9f1a92dd984d6040cc41ed06e273e.apk Result
      shell: bash
      # This sample should have 15 behaviors with 100% confidence
      run: |
        if [ "${{ env.e273e_RESULT }}" == "36" ]; then
          exit 0
        else
          exit 1
        fi
